import { shadcn } from '@clerk/themes';
import { basePath } from '@/lib/base-path';

export const clerkAppearance = {
  theme: shadcn,
  cssLayerName: 'clerk',
  options: {
    logoPlacement: 'inside' as const,
    logoLinkUrl: basePath || '/',
    logoImageUrl: `${window.location.origin}${basePath}/logo.svg`,
  },
  variables: {
    colorPrimary: '#c58b46',
    colorForeground: '#203b35',
    colorMutedForeground: '#6f7f79',
    colorDanger: '#be5b4d',
    colorBackground: '#fbf8f2',
    colorInput: '#ffffff',
    colorInputForeground: '#203b35',
    colorNeutral: '#d9ded6',
    fontFamily: 'DM Sans, sans-serif',
    borderRadius: '1rem',
  },
  elements: {
    rootBox: 'w-full flex justify-center',
    cardBox: 'bg-[#fbf8f2] rounded-[24px] w-[440px] max-w-full overflow-hidden shadow-2xl',
    card: '!shadow-none !border-0 !bg-transparent !rounded-none',
    footer: '!shadow-none !border-0 !bg-transparent !rounded-none',
    headerTitle: 'text-[#203b35] font-serif',
    headerSubtitle: 'text-[#6f7f79]',
    socialButtonsBlockButtonText: 'text-[#203b35]',
    formFieldLabel: 'text-[#203b35]',
    footerActionLink: 'text-[#2e8b79]',
    footerActionText: 'text-[#6f7f79]',
    dividerText: 'text-[#6f7f79]',
    formFieldSuccessText: 'text-[#2e8b79]',
    alertText: 'text-[#be5b4d]',
    logoBox: 'rounded-xl',
    logoImage: 'rounded-xl',
    socialButtonsBlockButton: 'border-[#d9ded6] bg-white hover:bg-[#f4efe6]',
    formButtonPrimary: 'bg-[#2e8b79] hover:bg-[#267666] text-white',
    formFieldInput: 'border-[#d9ded6] bg-white text-[#203b35]',
    footerAction: 'text-[#6f7f79]',
    dividerLine: 'bg-[#d9ded6]',
    alert: 'bg-[#fff1ed] border-[#f1c9c0]',
    otpCodeFieldInput: 'border-[#d9ded6] bg-white text-[#203b35]',
    formFieldRow: 'text-[#203b35]',
    main: 'bg-transparent',
  },
};
